<?php

return [
    'name' => 'Oriental Heritage Hall',
    'tagline' => 'Luxury banquet hall · Wedding & events venue',
    'phone' => env('VENUE_PHONE', ''),
    'whatsapp' => env('VENUE_WHATSAPP', ''),
    'email' => env('VENUE_EMAIL', 'enquiries@orientalheritagehall.co.uk'),
    'address' => env('VENUE_ADDRESS', 'London, United Kingdom'),
    'google_business_url' => env('GOOGLE_BUSINESS_URL', ''),
    'virtual_tour_url' => env('VIRTUAL_TOUR_URL', ''),
    'logo' => '/orientalheritagehall.jpeg',
    'hero_video' => null,
    'hero_poster' => '/orientalheritagehall.jpeg',
    'capacity' => [
        ['value' => '50–2,000', 'label' => 'Guests'],
        ['value' => 'Multiple', 'label' => 'Stage options'],
        ['value' => 'Flexible', 'label' => 'Catering options'],
        ['value' => 'Tailored', 'label' => 'Décor packages'],
    ],
    'spaces' => [
        ['name' => 'The Grand Hall', 'label' => 'A generous canvas', 'description' => 'A versatile, beautifully proportioned setting for ceremonies, receptions and large-scale celebrations.', 'class' => 'media-grand', 'image' => '/grand-hall.png'],
        ['name' => 'The Heritage Suite', 'label' => 'Intimate occasions', 'description' => 'A considered room for private dinners, family gatherings and smaller celebrations.', 'class' => 'media-suite', 'image' => '/heritage-suite.png'],
        ['name' => 'The Arrival Gallery', 'label' => 'First impressions', 'description' => 'A memorable entrance sequence for welcome drinks, photographs and a graceful guest arrival.', 'class' => 'media-arrival', 'image' => '/arrival-gallery.png'],
    ],
    'packages' => [
        ['name' => 'Silver', 'intro' => 'A considered foundation for an elegant celebration.', 'items' => ['Venue hire', 'Flexible guest capacity', 'Catering consultation', 'Essential stage provision', 'Event coordination']],
        ['name' => 'Gold', 'intro' => 'A beautifully balanced experience with room to personalise.', 'recommended' => true, 'items' => ['Venue hire', 'Enhanced catering selection', 'Food station options', 'Stage and lighting design', 'Décor consultation', 'Bridal suite', 'Event coordination']],
        ['name' => 'Platinum', 'intro' => 'A fully tailored celebration, shaped around your vision.', 'items' => ['Venue hire', 'Bespoke menu consultation', 'Curated food stations', 'Signature stage and décor', 'Lighting design', 'Bridal suite', 'Dedicated event coordination', 'Parking assistance']],
    ],
    'gallery' => [
        ['title' => 'A considered beginning', 'category' => 'Venue Details', 'class' => 'media-gallery-1'],
        ['title' => 'Room to make it yours', 'category' => 'Weddings', 'class' => 'media-gallery-2'],
        ['title' => 'The details guests remember', 'category' => 'Décor and Stages', 'class' => 'media-gallery-3'],
        ['title' => 'An evening in the making', 'category' => 'Private Parties', 'class' => 'media-gallery-4'],
        ['title' => 'Gather around the table', 'category' => 'Food and Catering', 'class' => 'media-gallery-5'],
        ['title' => 'A room for every occasion', 'category' => 'Corporate', 'class' => 'media-gallery-6'],
    ],
    'faqs' => [
        ['q' => 'How far in advance should we enquire?', 'a' => 'We recommend beginning the conversation as soon as you have a date in mind. Our team can talk through options even while plans are still taking shape.'],
        ['q' => 'Can the hall be styled around our celebration?', 'a' => 'Yes. Stage, lighting, table styling and entrance details can be shaped around your occasion and cultural traditions.'],
        ['q' => 'Do you offer menu tastings?', 'a' => 'Menu tastings and bespoke menu consultations can be arranged as part of your planning journey. Please share your requirements with the team.'],
        ['q' => 'Is a virtual tour available?', 'a' => 'A virtual-tour integration is ready for the venue’s confirmed 360° link. Until that link is supplied, you can enquire for a personal viewing.'],
    ],
    'reviews' => [],
    'navigation' => [
        ['key' => 'weddings', 'label' => 'Weddings', 'intro' => 'A beautifully timed day, shaped around your traditions and your people.', 'image' => '/weddingimg.webp', 'links' => [['label' => 'All weddings', 'href' => '/weddings'], ['label' => 'Pakistani weddings', 'href' => '/weddings#pakistani'], ['label' => 'Muslim weddings & Nikah', 'href' => '/weddings#nikah'], ['label' => 'Mehndi, Baraat & Walima', 'href' => '/weddings#celebrations'], ['label' => 'Indian, Hindu & Sikh weddings', 'href' => '/weddings#indian'], ['label' => 'Bengali, Turkish, African & Jewish weddings', 'href' => '/weddings#cultures'], ['label' => 'Asian weddings', 'href' => '/weddings#asian']]],
        ['key' => 'corporate', 'label' => 'Corporate events', 'intro' => 'A polished, adaptable setting for the moments that bring a company together.', 'image' => '/grand-hall.png', 'links' => [['label' => 'All corporate events', 'href' => '/corporate'], ['label' => 'Conferences & presentations', 'href' => '/corporate#conferences'], ['label' => 'Award ceremonies', 'href' => '/corporate#awards'], ['label' => 'Gala dinners & charity events', 'href' => '/corporate#gala'], ['label' => 'Exhibitions & product launches', 'href' => '/corporate#launches'], ['label' => 'Networking & company celebrations', 'href' => '/corporate#networking']]],
        ['key' => 'parties', 'label' => 'Private parties', 'intro' => 'A warm, flexible backdrop for celebrations that deserve a little theatre.', 'image' => '/heritage-suite.png', 'links' => [['label' => 'All private parties', 'href' => '/parties'], ['label' => 'Birthdays & anniversaries', 'href' => '/parties#birthdays'], ['label' => 'Engagements & graduations', 'href' => '/parties#engagements'], ['label' => 'Family celebrations', 'href' => '/parties#family'], ['label' => 'Gala dinners', 'href' => '/parties#gala']]],
        ['key' => 'spaces', 'label' => 'Spaces / venue', 'intro' => 'Flexible rooms, considered proportions and space to make it entirely your own.', 'image' => '/grand-hall.png', 'links' => [['label' => 'All spaces', 'href' => '/spaces'], ['label' => 'The Grand Hall', 'href' => '/spaces#grand-hall'], ['label' => 'The Heritage Suite', 'href' => '/spaces#heritage-suite'], ['label' => 'The Arrival Gallery', 'href' => '/spaces#arrival-gallery'], ['label' => 'Capacity & configurations', 'href' => '/spaces#capacity']]],
        ['key' => 'gallery', 'label' => 'Gallery', 'intro' => 'A glimpse into the atmosphere, details and possibilities of the venue.', 'image' => '/cuisine-feature.png', 'links' => [['label' => 'Photo gallery', 'href' => '/gallery'], ['label' => 'Weddings & celebrations', 'href' => '/gallery#weddings'], ['label' => 'Mehndi & Walima', 'href' => '/gallery#mehndi'], ['label' => 'Corporate & private parties', 'href' => '/gallery#events'], ['label' => 'Catering', 'href' => '/gallery#catering'], ['label' => 'Décor, stages & venue details', 'href' => '/gallery#decor']]],
        ['key' => 'catering', 'label' => 'Catering', 'intro' => 'A menu with its own sense of place, from live stations to thoughtful finishing touches.', 'image' => '/cuisine-feature.png', 'links' => [['label' => 'Explore catering', 'href' => '/catering']]],
        ['key' => 'decor', 'label' => 'Décor', 'intro' => 'From the entrance installation to the final lighting cue, every detail has a role.', 'image' => '/arrival-gallery.png', 'links' => [['label' => 'Explore décor & stages', 'href' => '/decor']]],
        ['key' => 'packages', 'label' => 'Packages', 'intro' => 'Three considered starting points, ready to be tailored around your occasion.', 'image' => '/heritage-suite.png', 'links' => [['label' => 'View packages', 'href' => '/packages']]],
        ['key' => 'tour', 'label' => 'Virtual tour', 'intro' => 'Step inside the possibilities before you arrive.', 'image' => '/grand-hall.png', 'links' => [['label' => 'Start virtual tour', 'href' => '/tour']]],
        ['key' => 'reviews', 'label' => 'Reviews', 'intro' => 'A place for genuine guest reflections, connected only when verified.', 'image' => '/weddingimg.webp', 'links' => [['label' => 'About our reviews', 'href' => '/reviews']]],
        ['key' => 'about', 'label' => 'About', 'intro' => 'A modern London venue with heritage at heart.', 'image' => '/arrival-gallery.png', 'links' => [['label' => 'Discover our approach', 'href' => '/about']]],
        ['key' => 'contact', 'label' => 'Contact', 'intro' => 'Tell us a little about your plans and let’s begin a conversation.', 'image' => '/heritage-suite.png', 'links' => [['label' => 'Make an enquiry', 'href' => '/contact']]],
    ],
];
