@extends('layouts.app')
@section('content')
<section class="hero"><div class="hero-media"></div><div class="hero-overlay"></div><div class="container hero-content"><p class="eyebrow light reveal">A distinguished London venue</p><h1 class="reveal delay-1">Celebrations<br><em>shaped by heritage.</em></h1><p class="hero-copy reveal delay-2">An exceptional setting for weddings, corporate occasions and unforgettable private celebrations.</p><div class="hero-buttons reveal delay-3"><a class="button" href="{{ route('page','contact') }}">Check availability <span>↗</span></a><a class="text-link light" href="#welcome">Explore the venue <span>↓</span></a></div></div><div class="hero-note">Oriental Heritage Hall <span>·</span> London, UK</div></section>
<section class="event-nav"><div class="container event-grid"><a href="{{ route('page','weddings') }}"><small>01</small><span>Weddings</span><b>↗</b></a><a href="{{ route('page','corporate') }}"><small>02</small><span>Corporate events</span><b>↗</b></a><a href="{{ route('page','parties') }}"><small>03</small><span>Private parties</span><b>↗</b></a></div></section>
<section class="section welcome" id="welcome"><div class="container split"><div><p class="eyebrow">Welcome to Oriental Heritage Hall</p><h2>A setting for <em>significant</em> moments.</h2></div><div><p class="lead">There is a certain feeling when you enter a room made for the occasion. At Oriental Heritage Hall, generous space, thoughtful detail and warm hospitality come together to make every gathering feel entirely your own.</p><a class="arrow-link" href="{{ route('page','about') }}">Discover our approach <span>→</span></a></div></div></section>
<section class="capacity-band"><div class="container"><div class="band-heading"><div><p class="eyebrow light">Designed around your occasion</p><h2>Room to gather,<br><em>space to make it yours.</em></h2></div><a class="button button-outline" href="{{ route('page','spaces') }}">Explore spaces</a></div><div class="stats">@foreach(config('venue.capacity') as $stat)<div class="stat"><strong>{{ $stat['value'] }}</strong><span>{{ $stat['label'] }}</span></div>@endforeach</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">The venue</p><h2>Three ways to<br><em>make an entrance.</em></h2></div><a class="arrow-link" href="{{ route('page','spaces') }}">View all spaces <span>→</span></a></div><div class="space-grid">@foreach(config('venue.spaces') as $space)<article class="space-card {{ $space['class'] }}" style="background-image:url('{{ asset($space['image']) }}')"><div class="space-card-content"><p class="eyebrow light">{{ $space['label'] }}</p><h3>{{ $space['name'] }}</h3><p>{{ $space['description'] }}</p></div></article>@endforeach</div></div></section>
<section class="feature-split"><div class="feature-copy"><p class="eyebrow">In-house catering</p><h2>Food that becomes part of the <em>occasion.</em></h2><p class="lead">Live food stations, Asian cuisine, British and international selections, canapés and desserts—planned around the rhythm of your celebration.</p><p class="muted">From the first welcome bite to the final plate, our catering conversation is shaped around your guests, your traditions and the atmosphere you want to create.</p><a class="button button-dark" href="{{ route('page','catering') }}">Explore catering <span>↗</span></a></div><div class="feature-image"><img src="{{ asset('cuisine-feature.png') }}" alt="A refined platter of South Asian grilled cuisine served at a wedding celebration" loading="lazy"></div></section>
<section class="section packages-preview"><div class="container"><div class="section-heading"><div><p class="eyebrow">The possibilities</p><h2>Three considered<br><em>ways to begin.</em></h2></div><p class="muted max-copy">Every celebration is different. Our packages give you a clear starting point, with space to tailor the details.</p></div><div class="package-grid">@foreach(config('venue.packages') as $package)<article class="package-card @if(!empty($package['recommended'])) featured @endif"><p class="eyebrow">{{ $package['name'] }} @if(!empty($package['recommended']))<span class="tag">Most chosen</span>@endif</p><h3>{{ $package['intro'] }}</h3><ul>@foreach($package['items'] as $item)<li>{{ $item }}</li>@endforeach</ul><p class="price-note">Price on request</p><a href="{{ route('page','contact') }}?package={{ $package['name'] }}" class="arrow-link">Request this package <span>→</span></a></article>@endforeach</div></div></section>
<section class="tour-strip"><div class="container tour-inner"><div><p class="eyebrow light">See it for yourself</p><h2>A sense of the <em>space.</em></h2><p class="light-text">Our virtual tour integration is ready for the confirmed 360° experience.</p></div><button class="button" data-tour-open>Start virtual tour <span>↗</span></button></div></section>
<section class="section review-section"><div class="container review-empty"><p class="eyebrow">Google reviews</p><h2>What our guests<br><em>will remember.</em></h2><p class="muted">Verified Google review content will appear here once the venue’s official business profile is connected.</p><a class="arrow-link" href="{{ route('page','reviews') }}">About our review process <span>→</span></a></div></section>
<section class="enquiry-cta"><div class="container split"><div><p class="eyebrow light">Begin a conversation</p><h2>Let’s make room<br>for <em>something special.</em></h2></div><div><p class="light-text lead">Tell us a little about your plans. We’ll help you find the right space, atmosphere and next step.</p><a class="button" href="{{ route('page','contact') }}">Make an enquiry <span>↗</span></a></div></div></section>
<div class="tour-modal" data-tour-modal role="dialog" aria-modal="true" aria-labelledby="tour-title" hidden><div class="tour-dialog"><button class="modal-close" data-tour-close aria-label="Close virtual tour">×</button><p class="eyebrow">Virtual tour</p><h2 id="tour-title">Your tour is being prepared.</h2><p class="muted">The confirmed 360° tour link will be connected here. In the meantime, enquire to arrange a personal viewing.</p><a class="button" href="{{ route('page','contact') }}">Arrange a viewing</a></div></div>
@endsection
