@extends('layouts.app')
@php
$titles = ['weddings'=>'Weddings with a sense of occasion','corporate'=>'Corporate events, considered beautifully','parties'=>'Private celebrations, made memorable','spaces'=>'A venue with room to become your own','catering'=>'Food made part of the experience','decor'=>'A stage for your story','packages'=>'A thoughtful place to begin','gallery'=>'A glimpse into the possibilities','tour'=>'Step inside Oriental Heritage Hall','about'=>'A modern venue with heritage at heart','reviews'=>'A promise to make every detail count','contact'=>'Let’s begin with your plans','privacy'=>'Privacy policy','cookies'=>'Cookie policy','terms'=>'Terms & conditions','accessibility'=>'Accessibility'];
$copy = ['weddings'=>'From intimate Nikah ceremonies to grand receptions, our spaces are shaped around the rhythm, traditions and people that make your day yours.','corporate'=>'A polished, adaptable setting for conferences, awards, galas, exhibitions and the moments that bring a company together.','parties'=>'Birthdays, anniversaries, engagements and family gatherings deserve a setting with warmth, flexibility and a little theatre.','spaces'=>'Flexible rooms, considered proportions and a calm planning process give you a confident canvas for an exceptional event.','catering'=>'Live food stations, Asian, British and international selections, canapés, desserts and thoughtful menu consultation.','decor'=>'From an arrival installation to the final lighting cue, we help create an atmosphere that feels intentional from every angle.','packages'=>'Three clear starting points, each open to a more personal conversation. Pricing remains on request until authentic venue rates are confirmed.','gallery'=>'Professional Oriental Heritage Hall photography will be added here as the venue media library is supplied.','tour'=>'Explore the architecture, proportions and possibilities from wherever you are. The confirmed 360° link will be connected here.','about'=>'Oriental Heritage Hall brings a modern London sensibility to celebrations rooted in family, culture and connection.','reviews'=>'We believe trust should be earned. Verified Google content will appear here once the official business profile is connected.','contact'=>'Share what you know so far and we’ll help you shape the next step.','privacy'=>'This editable template will be completed with the venue owner’s verified legal details before launch.','cookies'=>'Essential cookies keep the website working. Optional analytics will only be enabled after consent.','terms'=>'This editable template outlines the areas requiring owner and solicitor verification before publication.','accessibility'=>'We are committed to making this website and the venue enquiry journey accessible to as many people as possible.'];
$list = match ($page) {
    'weddings' => ['Pakistani weddings','Muslim weddings & Nikah','Mehndi, Baraat & Walima','Indian, Hindu & Sikh weddings','Bengali, Turkish, African & Jewish weddings','Asian weddings'],
    'corporate' => ['Conferences & presentations','Award ceremonies & gala dinners','Charity and networking events','Exhibitions & product launches','Theatre, banquet & cabaret layouts','Branding, AV & refreshment planning'],
    'parties' => ['Birthdays & anniversaries','Engagements & graduation celebrations','Family occasions & gala dinners','Décor, entertainment & dance floors','Flexible catering and food stations','A package shaped around you'],
    'catering' => ['Live food stations','Asian, British & international selections','Canapés, desserts & beverages','Dietary requirements discussed early','Menu tastings and consultations','A menu with its own sense of place'],
    'decor' => ['Wedding and Mehndi stages','Walima styling','Floral design & entrance installations','Table styling and chandeliers','Lighting and dance floors','Bespoke themes'],
    default => ['The Grand Hall','The Heritage Suite','Arrival Gallery','Flexible seating layouts','Catering and stage possibilities','A personal viewing'],
};
@endphp
@section('content')
<section class="page-hero"><div class="page-hero-mark"></div><div class="container"><p class="eyebrow">Oriental Heritage Hall · London</p><h1>{{ $titles[$page] }}</h1><p class="hero-copy">{{ $copy[$page] }}</p></div></section>
@if(in_array($page,['privacy','cookies','terms','accessibility']))
<section class="section prose-section"><div class="container narrow"><p class="eyebrow">Information</p><h2>Clear, considered and ready to be made specific.</h2><p>This page is an owner-editable content area. Business-specific legal wording, data controller details, retention periods and published contact information require verification before the site goes live.</p><p>For questions about an enquiry or your information, please contact <a href="mailto:{{ config('venue.email') }}">{{ config('venue.email') }}</a>.</p><div class="notice">Owner verification required before publication.</div></div></section>
@elseif($page === 'contact')
<section class="section"><div class="container form-layout"><div><p class="eyebrow">Availability request</p><h2>Tell us about<br><em>your occasion.</em></h2><p class="muted">This is an enquiry request, not live availability. We’ll respond with the next useful step.</p></div><form class="enquiry-form" action="{{ route('enquire.store') }}" method="POST">@csrf @if(session('success'))<div class="success">{{ session('success') }}</div>@endif @if($errors->any())<div class="error-summary">Please check the highlighted fields and try again.</div>@endif
<div class="form-grid"><label>Full name<input name="name" value="{{ old('name') }}" required></label><label>Email<input type="email" name="email" value="{{ old('email') }}" required></label><label>UK telephone<input name="phone" value="{{ old('phone') }}" placeholder="07xxx xxxxxx" required></label><label>Event type<select name="event_type" required><option value="">Select one</option><option>Wedding</option><option>Corporate event</option><option>Private party</option></select></label><label>Preferred date<input type="date" name="preferred_date" value="{{ old('preferred_date') }}"></label><label>Alternative date<input type="date" name="alternative_date" value="{{ old('alternative_date') }}"></label><label>Approximate guests<input type="number" name="guests" min="1" max="2000" value="{{ old('guests') }}" required></label><label>Preferred space<select name="space"><option value="">Open to guidance</option><option>The Grand Hall</option><option>The Heritage Suite</option></select></label><label class="full">Selected package<select name="package"><option value="">Open to guidance</option>@foreach(config('venue.packages') as $package)<option @selected(request('package') === $package['name'])>{{ $package['name'] }}</option>@endforeach</select></label><label class="full">Tell us about your plans<textarea name="message" rows="5">{{ old('message') }}</textarea></label></div><label class="consent"><input type="checkbox" name="consent" required> I consent to Oriental Heritage Hall using these details to respond to my enquiry.</label><button class="button" type="submit">Send enquiry <span>↗</span></button><p class="form-note">Your details are used for this enquiry only, subject to our privacy policy.</p></form></div></section>
@elseif($page === 'packages')
<section class="section"><div class="container package-grid">@foreach(config('venue.packages') as $package)<article class="package-card @if(!empty($package['recommended'])) featured @endif"><p class="eyebrow">{{ $package['name'] }} @if(!empty($package['recommended']))<span class="tag">Most chosen</span>@endif</p><h3>{{ $package['intro'] }}</h3><ul>@foreach($package['items'] as $item)<li>{{ $item }}</li>@endforeach</ul><p class="price-note">Request a tailored quotation</p><a href="{{ route('page','contact') }}?package={{ $package['name'] }}" class="button button-dark">Request {{ $package['name'] }}</a></article>@endforeach</div></section>
@elseif($page === 'gallery')
<section class="section"><div class="container"><div class="filter-row" data-gallery-filters><button class="active" data-filter="all">All</button>@foreach(['Weddings','Mehndi','Walima','Corporate','Private Parties','Food and Catering','Décor and Stages','Venue Details'] as $filter)<button data-filter="{{ $filter }}">{{ $filter }}</button>@endforeach</div><div class="gallery-grid" data-gallery>@foreach(config('venue.gallery') as $item)<button class="gallery-item {{ $item['class'] }}" style="background-image:url('{{ asset($item['image']) }}')" data-category="{{ $item['category'] }}" data-title="{{ $item['title'] }}" data-image="{{ asset($item['image']) }}"><span>{{ $item['title'] }}</span><small>{{ $item['category'] }}</small></button>@endforeach</div><div class="gallery-note">Images shown are part of the Oriental Heritage Hall visual library.</div></div></section><div class="lightbox" data-lightbox hidden><button data-lightbox-close aria-label="Close gallery">×</button><div><img data-lightbox-image alt=""><p class="eyebrow light">Gallery</p><h2 data-lightbox-title></h2><p class="light-text">Oriental Heritage Hall</p></div></div>
@elseif($page === 'tour')
<section class="section"><div class="container tour-page"><div class="tour-preview"><div class="tour-play">360°</div><p class="eyebrow light">Immersive preview</p><h2>See the space<br><em>before you arrive.</em></h2></div><div class="tour-details"><p class="lead">The virtual tour is prepared as a dedicated, mobile-friendly experience. Once the venue’s confirmed 360° URL is available, it will load only when requested.</p><button class="button" data-tour-open>Start virtual tour <span>↗</span></button><a class="arrow-link" href="{{ route('page','contact') }}">Arrange a personal viewing <span>→</span></a></div></div></section>
@elseif($page === 'reviews')
<section class="section"><div class="container empty-state"><div class="empty-mark">✦</div><p class="eyebrow">Verified content only</p><h2>A place for genuine<br><em>guest reflections.</em></h2><p class="muted">Google Business details, review text, dates and author names will be displayed once an authorised integration is connected. No testimonials are invented here.</p>@if(config('venue.google_business_url'))<a class="button" href="{{ config('venue.google_business_url') }}" target="_blank" rel="noopener">View on Google</a>@else<p class="notice">Google Business profile link to be supplied.</p>@endif</div></section>
@else
<section class="section"><div class="container content-columns"><div><h2>{{ $page === 'weddings' ? 'Tradition, atmosphere and a beautifully timed day.' : 'A thoughtful approach to every detail.' }}</h2><a class="button" href="{{ route('page','contact') }}">Enquire about your event <span>↗</span></a></div><div class="content-list">@foreach($list as $item)<div class="list-row"><span>0{{ $loop->iteration }}</span><h3>{{ $item }}</h3><b>↗</b></div>@endforeach</div></div></section>
@endif
<div class="tour-modal" data-tour-modal role="dialog" aria-modal="true" hidden><div class="tour-dialog"><button class="modal-close" data-tour-close aria-label="Close virtual tour">×</button><p class="eyebrow">Virtual tour</p><h2>Your tour is being prepared.</h2><p class="muted">The confirmed 360° tour link will be connected here. In the meantime, enquire to arrange a personal viewing.</p><a class="button" href="{{ route('page','contact') }}">Arrange a viewing</a></div></div>
@endsection
